name: CI

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    name: Run tests
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.validate-fails-test.outputs.response }}
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2

      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest discover -s tests

      - name: Validate fails tests
        id: validate-fails-test
        if: ${{ failure() }}
        env:
          MESSAGE: Bummer
        run: echo "::set-output name=response::${MESSAGE}"

      - name: Validate success tests
        id: validate-success-test
        if: ${{ success() }}
        env:
          MESSAGE: Ok
        run: echo "::set-output name=response::${MESSAGE}"

      - name: calculate coverage
        run: |
          coverage run -m unittest discover -s tests
          coverage report -m
  job2:
    name: print some text
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: print
        id: print
        run: |
          echo "Failed: $${{ needs.job1.outputs.message }}"
          echo "Success: $${{ needs.job1.outputs.message }}"
